# префикс для всех переменных
[1.3]

# 1.3.4.23.66 это OCTET STRING
4.23.66 = "hello world"

# Эта переменная типа INTEGER, которую можно поменять через SetPDU
4.23.67.mutable = 23

# Это IP адрес
45.67.7.123.ip = '127.0.0.1'

# Это ещё один IP адрес, который можно поменять
45.67.7.124.mutable.ip = '192.168.0.1'

# Timeticks переменная
45.31 = 1979-05-27T00:32:00.999999
